language: c

services:
- docker

before_install:
- docker pull bitcraze/builder
#- docker run -it --rm -v ${PWD}:/module bitcraze/builder gcc main.c -o main
- docker run -it --rm --mount type=bind,src=${PWD},dst=/module bitcraze/builder make
script:
- ./hello

